Remove socket.io dependency
tenfold/timesync pull request #2
Opened 2022-01-26 17:52 UTC by louishawkins

Socket.io is only being used in the "examples" in this repo. Since it's in dependencies it gets installed in the clients as a transitive dependency which is not needed. There have been security vulnerability alerts generated in the app due to this.

This PR simply removes the dependency since it's only used in an example. It can be added to devDependencies if we really want it, but I'd opt to just skip it.

2022-07-14 16:08 UTC, Ventrae approved these changes

2022-07-18 16:29 UTC, danego approved these changes

2022-07-18 19:27 UTC, kessiler requested changes

2022-07-18 19:27 UTC, kessiler commented on package.json
> +    "babel-core": "^6.26.3",
Seems like you can move most dependencies here to devDependencies.
babel core, babelify, body-parser, debug, express, etc...

2022-11-21 09:17 UTC, mocarz approved these changes

2022-11-21 15:02 UTC, merged